import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, CalendarDays, Check, Clock3, FileText, Megaphone, Paperclip, Plus, Search, Send, Trash2, Users, X } from "lucide-react";
import { api, errorText } from "../../services/api";

type Person = { id: string; name: string; email: string | null; phone: string | null; company: string | null; role: string };
type Template = { id: string; title: string; body: string; priority: string };
type Announcement = { id: string; title: string; body: string; audience: string; priority: string; createdAt: string; attachments: Array<{ id: string; originalName: string; size: number }>; deliveries: Array<{ status: string; error: string | null }> };
type Data = { announcements: Announcement[]; templates: Template[] };
const roleName: Record<string, string> = { CUSTOMER: "Müşteri", SUPERVISOR: "Sorumlu", AGENT: "Destek uzmanı" };
const audienceName: Record<string, string> = { CUSTOMERS: "Müşteriler", STAFF: "Personel", ALL: "Tüm kullanıcılar", PERSON: "Tek kişi" };
const priorityName: Record<string, string> = { LOW: "Bilgilendirme", NORMAL: "Normal", HIGH: "Önemli", URGENT: "Acil" };
const presets = [
  { title: "Planlı bakım duyurusu", body: "Merhaba,\n\nSistemimizde planlı bakım çalışması yapılacaktır. Bu süre boyunca kısa süreli erişim kesintileri yaşanabilir.\n\nAnlayışınız için teşekkür ederiz." },
  { title: "Etkinlik daveti", body: "Merhaba,\n\nSizi yaklaşan etkinliğimize davet ediyoruz. Katılım ve detaylar için bu duyuruyu takip edebilirsiniz.\n\nGörüşmek üzere!" },
  { title: "Toplantı hatırlatması", body: "Merhaba,\n\nToplantı hatırlatması: Lütfen toplantı saatinden birkaç dakika önce hazır olun.\n\nKatılımınız için teşekkürler." },
];

export function AnnouncementsPage() {
  const client = useQueryClient();
  const [audience, setAudience] = useState("CUSTOMERS");
  const [recipientId, setRecipientId] = useState("");
  const [channels, setChannels] = useState<string[]>(["APP"]);
  const [preview, setPreview] = useState<Announcement | null>(null);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [eventAt, setEventAt] = useState("");
  const data = useQuery({ queryKey: ["/announcements"], queryFn: async () => (await api.get<{ data: Data }>("/announcements")).data.data });
  const people = useQuery({ queryKey: ["/announcements/recipients"], queryFn: async () => (await api.get<{ data: Person[] }>("/announcements/recipients")).data.data });
  const filteredPeople = useMemo(() => people.data?.filter(person => audience === "CUSTOMERS" ? person.role === "CUSTOMER" : audience === "STAFF" ? person.role !== "CUSTOMER" : true) ?? [], [people.data, audience]);
  const send = useMutation({ mutationFn: (form: FormData) => api.post("/announcements", form), onSuccess: async response => { const result = response.data.data; setSuccess(`${result.deliveredCount}/${result.recipientCount} alıcıya duyuru iletildi.`); setError(""); setTimeout(() => setSuccess(""), 6000); await client.invalidateQueries({ queryKey: ["/announcements"] }); await client.invalidateQueries({ queryKey: ["/notifications"] }); }, onError: (e: unknown) => setError(errorText(e)) });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/announcements/${id}`), onSuccess: () => void client.invalidateQueries({ queryKey: ["/announcements"] }) });
  const removeTemplate = useMutation({ mutationFn: (id: string) => api.delete(`/announcement-templates/${id}`), onSuccess: () => void client.invalidateQueries({ queryKey: ["/announcements"] }) });
  function applyTemplate(template: Pick<Template, "title" | "body" | "priority">) {
    const form = document.querySelector<HTMLFormElement>("#announcement-compose");
    if (!form) return;
    (form.elements.namedItem("title") as HTMLInputElement).value = template.title;
    (form.elements.namedItem("body") as HTMLTextAreaElement).value = template.body;
    (form.elements.namedItem("priority") as HTMLSelectElement).value = template.priority;
    form.scrollIntoView({ behavior: "smooth", block: "start" });
  }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const source = new FormData(event.currentTarget);
    const files = source.getAll("files").filter(value => value instanceof File && value.size > 0);
    const form = new FormData();
    for (const [key, value] of source.entries()) if (key !== "files" && key !== "saveTemplate") form.append(key, value);
    form.append("audience", audience);
    if (recipientId) form.append("recipientId", recipientId);
    form.append("channels", JSON.stringify(channels));
    form.append("saveTemplate", String(source.get("saveTemplate") === "on"));
    if (eventAt) form.append("eventAt", new Date(eventAt).toISOString());
    for (const file of files) form.append("files", file);
    send.mutate(form);
  }
  const audienceCount = audience === "PERSON" ? 1 : filteredPeople.length;
  return <main className="announcements-page">
    <section className="announcement-hero"><div className="announcement-hero-glow"/><div className="announcement-hero-icon"><Megaphone size={25}/></div><div className="announcement-hero-copy"><span>İLETİŞİM MERKEZİ</span><h1>Duyurular</h1><p>Doğru mesajı, doğru kişilere ve doğru kanaldan ulaştırın.</p></div><div className="announcement-hero-stats"><div><strong>{data.data?.announcements.length ?? 0}</strong><span>Son duyuru</span></div><div><strong>{people.data?.length ?? 0}</strong><span>Ulaşılabilir kişi</span></div></div></section>
    <div className="announcement-layout"><div className="announcement-main-column">
      <form id="announcement-compose" className="announcement-card announcement-compose" onSubmit={submit}>
        <div className="announcement-section-heading"><span className="announcement-step">01</span><div><h2>Yeni duyuru oluştur</h2><p>İçeriği hazırla, hedefi ve gönderim kanallarını seç.</p></div></div>
        <div className="announcement-template-strip"><div className="announcement-strip-title"><FileText size={16}/>Hazır şablonlar</div>{presets.map(preset=><button key={preset.title} className="announcement-preset" type="button" onClick={()=>applyTemplate({...preset,priority:"NORMAL"})}>{preset.title}<Plus size={14}/></button>)}{data.data?.templates.map(template=><span className="announcement-template-chip" key={template.id}><button type="button" onClick={()=>applyTemplate(template)}>{template.title}</button><button type="button" aria-label={`${template.title} şablonunu sil`} onClick={()=>removeTemplate.mutate(template.id)}><X size={13}/></button></span>)}</div>
        <div className="announcement-field-grid"><label className="announcement-field announcement-full-field">Duyuru başlığı<input name="title" required minLength={3} maxLength={191} placeholder="Örn. Planlı sistem bakımı hakkında"/><small>Başlık alıcılara bildirim ve e-posta konusu olarak gösterilir.</small></label><label className="announcement-field announcement-full-field">Duyuru içeriği<textarea name="body" required minLength={1} maxLength={10000} rows={6} placeholder="Duyurunuzun ayrıntılarını yazın…"/><small>Net, anlaşılır ve gerekli bilgileri içeren bir mesaj hazırlayın.</small></label>
          <label className="announcement-field">Öncelik<select name="priority" defaultValue="NORMAL"><option value="LOW">Bilgilendirme</option><option value="NORMAL">Normal</option><option value="HIGH">Önemli</option><option value="URGENT">Acil</option></select></label>
          <label className="announcement-field">Hedef kitle<select value={audience} onChange={event=>{setAudience(event.target.value);setRecipientId("")}}><option value="CUSTOMERS">Tüm müşteriler</option><option value="STAFF">Personel</option><option value="ALL">Personel ve müşteriler</option><option value="PERSON">Tek kişi seç</option></select></label>
          {audience === "PERSON" && <label className="announcement-field announcement-full-field">Alıcı ara ve seç<div className="announcement-recipient-select"><Search size={16}/><select required value={recipientId} onChange={event=>setRecipientId(event.target.value)}><option value="">Kişi seçin…</option>{people.data?.map(person=><option key={person.id} value={person.id}>{person.name} · {roleName[person.role]}{person.company ? ` · ${person.company}` : ""}</option>)}</select></div></label>}
        </div>
        <label className="announcement-field announcement-event-time">Etkinlik veya toplantı tarihi ve saati <span>(isteğe bağlı)</span><input type="datetime-local" value={eventAt} onChange={event=>setEventAt(event.target.value)}/></label>
        <div className="announcement-channel-heading"><div><span className="announcement-step">02</span><div><h3>Gönderim kanalları</h3><p>Bir veya birkaç kanalı aynı anda kullanabilirsin.</p></div></div><span className="announcement-channel-selection">{channels.length} kanal seçildi</span></div>
        <div className="announcement-channels">{[{id:"APP",title:"Uygulama bildirimi",sub:"Bildirim kutusunda anında görünür",icon:<BellRing size={18}/>,ready:true},{id:"EMAIL",title:"E-posta",sub:"Alıcının kayıtlı e-posta adresine gider",icon:<span className="announcement-mail-icon">@</span>,ready:true},{id:"SMS",title:"SMS",sub:"Alıcının telefonuna kısa mesaj olarak gider",icon:<span className="announcement-sms-icon">SMS</span>,ready:true}].map(channel=><button className={`announcement-channel${channels.includes(channel.id)?" selected":""}`} type="button" key={channel.id} aria-pressed={channels.includes(channel.id)} onClick={()=>setChannels(current=>current.includes(channel.id)?current.filter(item=>item!==channel.id):[...current,channel.id])}><span className="announcement-channel-check">{channels.includes(channel.id)&&<Check size={13}/>}</span><span className="announcement-channel-symbol">{channel.icon}</span><span className="announcement-channel-text"><strong>{channel.title}</strong><small>{channel.sub}</small></span><span className={`announcement-ready${channel.id.toLowerCase()}`}>Seçilebilir</span></button>)}</div>
        <div className="announcement-delivery-note"><Users size={17}/><span><strong>{audience === "PERSON" ? (filteredPeople.find(person=>person.id===recipientId)?.name ?? "Alıcı bekleniyor") : audienceName[audience]}</strong> · {audience === "PERSON" && recipientId ? 1 : audienceCount} alıcı hedefleniyor</span></div>
        <label className="announcement-attachment"><Paperclip size={17}/><span><strong>Dosya veya ek yükle</strong><small>PDF, Word, Excel, görsel, TXT veya ZIP · dosya başına en fazla 25 MB</small></span><input type="file" name="files" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.docx,.xlsx,.txt,.zip"/></label>
        <label className="announcement-save-template"><input name="saveTemplate" type="checkbox"/><span>Bu duyuruyu daha sonra kullanmak için şablon olarak kaydet</span></label>
        {error&&<div className="announcement-alert error" role="alert">{error}</div>}{success&&<div className="announcement-alert success" role="status">{success}</div>}
        <div className="announcement-compose-footer"><span><Clock3 size={15}/> Gönderim hemen başlatılır</span><button className="announcement-send-button" type="submit" disabled={send.isPending||!channels.length||audienceCount===0||audience==="PERSON"&&!recipientId}>{send.isPending?<><span className="announcement-spinner"/>Gönderiliyor…</>:<><Send size={16}/>Duyuruyu gönder</>}</button></div>
      </form>
      <section className="announcement-card announcement-history"><div className="announcement-section-heading"><span className="announcement-step">03</span><div><h2>Gönderim geçmişi</h2><p>Son gönderilen duyuruları ve teslimat özetlerini takip edin.</p></div></div>{data.isLoading?<div className="announcement-empty">Duyurular yükleniyor…</div>:!data.data?.announcements.length?<div className="announcement-empty"><div><Megaphone size={20}/></div><strong>Henüz duyuru yok</strong><span>İlk duyurunu oluşturduğunda gönderim geçmişin burada görünür.</span></div>:<div className="announcement-list">{data.data.announcements.map(item=>{const sent=item.deliveries.filter(d=>d.status==="SENT").length;const partial=item.deliveries.filter(d=>d.status==="PARTIAL").length;const failed=item.deliveries.filter(d=>d.status==="FAILED").length;return <article className="announcement-history-item" key={item.id}><button className="announcement-history-copy" type="button" onClick={()=>setPreview(item)}><span className={`announcement-priority-dot ${item.priority.toLowerCase()}`}/><span className="announcement-history-text"><strong>{item.title}</strong><small>{audienceName[item.audience]??item.audience} · {new Date(item.createdAt).toLocaleString("tr-TR",{dateStyle:"medium",timeStyle:"short"})}</small></span><span className="announcement-delivery-count"><strong>{sent} başarılı</strong><small>{partial?`${partial} kısmi · `:""}{failed?`${failed} başarısız`:"teslimat"}</small></span></button>{item.attachments.length>0&&<span className="announcement-file-count"><Paperclip size={12}/>{item.attachments.length}</span>}<button className="announcement-delete" type="button" title="Duyuruyu sil" aria-label="Duyuruyu sil" onClick={()=>{if(window.confirm("Bu duyuru ve teslimat geçmişi silinsin mi?"))remove.mutate(item.id)}}><Trash2 size={15}/></button></article>})}</div>}</section>
    </div><aside className="announcement-aside"><section className="announcement-side-card"><div className="announcement-side-title"><CalendarDays size={18}/><h3>Hedef kitle</h3></div><p>Gönderimi doğru kişilere ulaştırmak için önceden filtreleyin.</p><div className="announcement-audience-list">{[{name:"Müşteriler",key:"CUSTOMERS",icon:"M"},{name:"Personel",key:"STAFF",icon:"P"},{name:"Herkes",key:"ALL",icon:"T"}].map(item=><div key={item.key}><span className={`announcement-audience-avatar ${item.key.toLowerCase()}`}>{item.icon}</span><span>{item.name}</span><strong>{item.key==="CUSTOMERS"?people.data?.filter(person=>person.role==="CUSTOMER").length??0:item.key==="STAFF"?people.data?.filter(person=>person.role!=="CUSTOMER").length??0:people.data?.length??0}</strong></div>)}</div><div className="announcement-side-foot"><Users size={14}/>Aktif kayıtlar üzerinden hedeflenir</div></section>
      <section className="announcement-side-card"><div className="announcement-side-title"><FileText size={18}/><h3>Şablon kütüphanesi</h3></div><p>Yaygın duyuruları tek tıkla doldur, sonra ihtiyacına göre düzenle.</p><div className="announcement-template-list">{presets.map((item,index)=><button key={item.title} type="button" onClick={()=>applyTemplate({...item,priority:"NORMAL"})}><span>{index===0?<SettingsIcon/>:index===1?<CalendarDays size={16}/>:<Clock3 size={16}/>}</span><span><strong>{item.title}</strong><small>Hazır şablon · düzenlenebilir</small></span><Plus size={15}/></button>)}</div><div className="announcement-side-foot"><Check size={14}/>Kendi şablonlarını da kaydedebilirsin</div></section>
      <section className="announcement-tip-card"><span><Megaphone size={17}/></span><strong>İyi duyuru için küçük ipucu</strong><p>Başlıkta konuyu net söyle, önemli tarih ve saatleri ilk paragrafta paylaş.</p></section>
    </aside></div>
    {preview&&<div className="announcement-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(null)}}><section className="announcement-preview-modal" role="dialog" aria-modal="true" aria-labelledby="announcement-preview-title"><header><span className="announcement-preview-icon"><Megaphone size={20}/></span><div><span>DUYURU DETAYI</span><h2 id="announcement-preview-title">Gönderim özeti</h2></div><button type="button" onClick={()=>setPreview(null)} aria-label="Kapat"><X size={18}/></button></header><div className="announcement-preview-content"><span className={`announcement-priority-pill ${preview.priority.toLowerCase()}`}>{priorityName[preview.priority]}</span><h3>{preview.title}</h3><p>{preview.body}</p><div className="announcement-preview-meta"><span><Users size={15}/>{audienceName[preview.audience]}</span><span><CalendarDays size={15}/>{new Date(preview.createdAt).toLocaleString("tr-TR",{dateStyle:"long",timeStyle:"short"})}</span></div>{preview.attachments.map(file=><a className="announcement-preview-file" key={file.id} href={`/api/v1/announcements/attachments/${file.id}`} target="_blank" rel="noreferrer"><Paperclip size={14}/>{file.originalName}</a>)}<div className="announcement-preview-status"><strong>Teslimat</strong><span className="sent">{preview.deliveries.filter(item=>item.status==="SENT").length} başarılı</span><span className="partial">{preview.deliveries.filter(item=>item.status==="PARTIAL").length} kısmi</span><span className="failed">{preview.deliveries.filter(item=>item.status==="FAILED").length} başarısız</span></div>{preview.deliveries.some(item=>item.error)&&<details className="announcement-preview-errors"><summary>Gönderim sorunlarını görüntüle</summary>{preview.deliveries.filter(item=>item.error).map((item,index)=><p key={index}>{item.error}</p>)}</details>}</div></section></div>}
  </main>;
}
function SettingsIcon(){return <FileText size={16}/>}
