import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, Megaphone, Paperclip, Users } from "lucide-react";
import { api } from "../../services/api";
import "./management.css";
type Announcement = { id: string; title: string; body: string; audience: string; priority: string; createdAt: string; eventAt?: string | null; author: { name: string }; attachments: Array<{ id: string; originalName: string; size: number }>; deliveries: Array<{ status: string; channels: string }> };
const audienceName: Record<string, string> = { CUSTOMERS: "Müşteriler", STAFF: "Personel", ALL: "Tüm kullanıcılar", PERSON: "Tek kişi" };
const priorityName: Record<string, string> = { LOW: "Bilgilendirme", NORMAL: "Normal", HIGH: "Önemli", URGENT: "Acil" };
export function AnnouncementInboxPage() {
  const [selected, setSelected] = useState<Announcement | null>(null);
  const query = useQuery({ queryKey: ["/announcements", "mine"], queryFn: async () => (await api.get<{ data: { announcements: Announcement[] } }>("/announcements")).data.data.announcements });
  const items = query.data ?? [];
  return <main className="announcements-page announcement-inbox-page"><section className="announcement-hero"><div className="announcement-hero-icon"><Megaphone size={25}/></div><div className="announcement-hero-copy"><span>BİLGİLENDİRMELER</span><h1>Duyurular</h1><p>Size iletilen güncel duyuru ve bilgilendirmeler.</p></div><div className="announcement-hero-stats"><div><strong>{items.length}</strong><span>Size iletilen</span></div></div></section><section className="announcement-card announcement-inbox-list">{query.isLoading?<div className="announcement-empty">Duyurular yükleniyor…</div>:!items.length?<div className="announcement-empty"><div><Megaphone size={20}/></div><strong>Şimdilik duyuru yok</strong><span>Size iletilen duyurular burada görünecek.</span></div>:items.map(item=><button className="announcement-inbox-row" type="button" key={item.id} onClick={()=>setSelected(item)}><span className={`announcement-priority-dot ${item.priority.toLowerCase()}`}/><span className="announcement-history-text"><strong>{item.title}</strong><small>{item.author.name} · {new Date(item.createdAt).toLocaleString("tr-TR",{dateStyle:"medium",timeStyle:"short"})}</small></span><span className={`announcement-priority-pill ${item.priority.toLowerCase()}`}>{priorityName[item.priority]??item.priority}</span></button>)}</section>{selected&&<div className="announcement-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="announcement-preview-modal" role="dialog" aria-modal="true" aria-labelledby="announcement-inbox-title"><header><span className="announcement-preview-icon"><Megaphone size={20}/></span><div><span>DUYURU · {priorityName[selected.priority]??selected.priority}</span><h2 id="announcement-inbox-title">Size iletilen duyuru</h2></div><button type="button" onClick={()=>setSelected(null)} aria-label="Kapat">×</button></header><div className="announcement-preview-content"><h3>{selected.title}</h3><p>{selected.body}</p><div className="announcement-preview-meta"><span><Users size={15}/>{selected.author.name}</span><span><CalendarDays size={15}/>{new Date(selected.createdAt).toLocaleString("tr-TR",{dateStyle:"long",timeStyle:"short"})}</span><span>{audienceName[selected.audience]??selected.audience}</span></div>{selected.attachments.map(file=><a className="announcement-preview-file" key={file.id} href={`/api/v1/announcements/attachments/${file.id}`} target="_blank" rel="noreferrer"><Paperclip size={14}/>{file.originalName}</a>)}</div></section></div>}</main>;
}
