export type KnowledgeTopic = {
  id: string;
  category: string;
  title: string;
  summary: string;
  points: string[];
  required: string[];
  note: string;
  verificationRequired?: boolean;
};

const topic = (
  id: string,
  category: string,
  title: string,
  summary: string,
  points: string[],
  required: string[],
  note: string,
  verificationRequired = true,
): KnowledgeTopic => ({
  id,
  category,
  title,
  summary,
  points,
  required,
  note,
  verificationRequired,
});

export const projectKnowledge: Record<"etic7" | "anypay", KnowledgeTopic[]> = {
  anypay: [
    topic(
      "anypay-hakkinda",
      "Başlangıç",
      "ANYPAY hakkında",
      "Ödeme ve tahsilat süreçlerini merkezi olarak yönetmeyi amaçlayan yapının genel kapsamı.",
      [
        "Online tahsilat ve Sanal POS yönetimi",
        "BIN kontrolü, POS yönlendirmesi, taksit ve komisyon",
        "Link, QR, bayi, mobil tahsilat, mutabakat ve raporlama",
        "ERP ve muhasebe bağlantıları",
      ],
      ["Kullanılan kanal", "İşyeri veya bayi", "İşlem amacı"],
      "Bu başlık ürünün genel kapsamını açıklar; tek tek özelliklerin aktifliği ilgili ekranda doğrulanmalıdır.",
      false,
    ),
    topic(
      "odeme-tahsilat",
      "Ödemeler",
      "Ödeme ve tahsilat işlemleri",
      "Bir ödeme kaydında görülebilecek temel bilgilerin nasıl okunacağını açıklar.",
      [
        "İşlem numarası, tarih-saat ve tutar",
        "İşlem durumu ve kullanılan ödeme kanalı",
        "Banka/ödeme kuruluşu, taksit ve komisyon",
        "İşlem sonucu ile banka sonucunun karşılaştırılması",
      ],
      ["İşlem/ödeme referansı", "Tarih-saat ve tutar", "Görünen durum"],
      "Ekranda bulunmayan alan veya durum adı eklenmemeli; gerçek AnyPay arayüzündeki değer esas alınmalıdır.",
    ),
    topic(
      "odeme-durumlari",
      "Ödemeler",
      "Ödeme durumları",
      "Başarılı, başarısız, bekleyen, iptal veya iade gibi durumların kullanıcı açısından anlamı.",
      [
        "Başarılı: tahsilat ve sistem kaydı birlikte doğrulanır",
        "Başarısız: banka/PSP hata sonucu incelenir",
        "Bekliyor: kesin sonuç gelmeden işlem tekrarlanmaz",
        "İptal/iade: ilk işlem ve geri ödeme kaydı birlikte izlenir",
      ],
      ["İşlem referansı", "Ekrandaki gerçek durum kodu", "Banka/PSP sonucu"],
      "Yalnızca uygulamada gerçekten kullanılan durumlar gösterilmelidir.",
    ),
    topic(
      "basarisiz-odeme",
      "Sorun giderme",
      "Başarısız ödeme işlemleri",
      "Ödeme başarısız olduğunda tekrar denemeden önce yapılacak kontroller.",
      [
        "Banka/POS ve ödeme durumu",
        "Hata mesajı veya hata kodu",
        "3D Secure sonucu",
        "Banka/PSP tarafından döndürülen kesin sonuç",
      ],
      ["İşlem numarası", "Tarih-saat ve tutar", "Banka/POS", "Hata mesajı"],
      "İşlem sonucu doğrulanmadan tekrar ödeme yapmak mükerrer tahsilata yol açabilir.",
      false,
    ),
    topic(
      "tutar-cekildi",
      "Sorun giderme",
      "Karttan tutar çekildi, işlem tamamlanmadı",
      "Banka tarafında tahsilat görünürken AnyPay kaydı tamamlanmadığında izlenecek yol.",
      [
        "Banka/PSP sonucu ile AnyPay durumunu karşılaştırın",
        "3D dönüşünün işlenip işlenmediğini kontrol edin",
        "Failover/retry sonucunda ikinci işlem oluşmadığını doğrulayın",
      ],
      [
        "İşlem numarası",
        "Tarih-saat ve tutar",
        "İlgili banka/POS",
        "Ekranda görünen durum",
      ],
      "Kesin sonuç doğrulanmadan yeniden tahsilat başlatılmamalıdır.",
      false,
    ),
    topic(
      "3d-secure",
      "Ödemeler",
      "3D Secure",
      "Kart sahibinin banka üzerinden doğrulandığı ödeme adımındaki yaygın durumlar.",
      [
        "Doğrulama ekranının açılması",
        "SMS veya doğrulama adımı",
        "Doğrulama sonrası sisteme dönüş",
        "Banka tarafından reddedilen işlem",
      ],
      ["İşlem referansı", "3D sonucu", "Hata kodu", "Tarayıcı/cihaz"],
      "Banka doğrulaması başarılı olsa bile ödeme sonucunun ayrıca kontrol edilmesi gerekir.",
    ),
    topic(
      "sanal-pos",
      "Yapılandırma",
      "Sanal POS yönetimi",
      "Sanal POS bağlantısı, çalışma durumu, taksit ve komisyon ayarlarının kapsamı.",
      [
        "POS tanımı ve aktif/pasif durumu",
        "Banka veya PSP bağlantısı",
        "Taksit ve komisyon ayarları",
        "POS hata mesajları ve geçen işlemler",
      ],
      ["POS/banka adı", "İşyeri kaydı", "Hata mesajı", "Test işlem zamanı"],
      "Kurulum adımları ve alan adları gerçek AnyPay arayüzü görülmeden kesinleştirilmemelidir.",
    ),
    topic(
      "bin",
      "Yönlendirme",
      "BIN kontrolü",
      "Kartın maskeli BIN bilgisinin banka, kart türü ve ödeme koşullarını belirlemedeki rolü.",
      [
        "Kart ve banka eşleşmesi",
        "Bireysel/ticari kart değerlendirmesi",
        "Taksit koşulları",
        "Uygun ödeme kanalının belirlenmesi",
      ],
      [
        "Yalnızca ilk 6-8 ve son 4 hane",
        "Beklenen banka/kart türü",
        "Görünen taksit/POS",
      ],
      "Tam kart numarası veya CVV hiçbir zaman paylaşılmamalıdır.",
    ),
    topic(
      "smart-routing",
      "Yönlendirme",
      "Akıllı POS yönlendirme",
      "Ödemenin kart, banka, taksit, maliyet ve kullanılabilirlik koşullarına göre uygun POS'a gönderilmesi.",
      [
        "POS kullanılabilirliği",
        "Kart/banka uyumluluğu",
        "Taksit ve komisyon koşulları",
        "Alternatif POS seçimi",
      ],
      ["İşlem referansı", "Seçilen ve beklenen POS", "Taksit/komisyon sonucu"],
      "Kullanıcıya kararın sonucu açıklanmalı; hassas algoritma ve güvenlik detayları gösterilmemelidir.",
    ),
    topic(
      "failover",
      "Yönlendirme",
      "Failover ve alternatif POS",
      "Bir ödeme kanalındaki teknik problemde alternatif kanalın devreye girme mantığı.",
      [
        "İlk POS sonucu",
        "Alternatif POS'un devreye girme koşulu",
        "Retry/failover işlem durumu",
        "Mükerrer tahsilatı önleyen kontrol",
      ],
      ["İşlem referansı", "İlk ve ikinci POS", "İki kanalın sonuçları"],
      "Failover aktif değilse bu bölüm çalışan özellik olarak sunulmamalıdır.",
    ),
    topic(
      "taksit-komisyon",
      "Ödemeler",
      "Taksit ve komisyon",
      "Banka, POS, müşteri veya şubeye göre sunulan taksit ve komisyon bilgisinin değerlendirilmesi.",
      [
        "Görüntülenen taksit seçenekleri",
        "Banka/POS koşulları",
        "Komisyon oranı ve hesaplama sonucu",
        "Görünmeyen taksit veya beklenmeyen komisyon",
      ],
      [
        "Müşteri/şube",
        "Kart bankası",
        "Seçilen POS",
        "Beklenen ve görünen oran",
      ],
      "Hesaplama örnekleri gerçek AnyPay kuralı doğrulandıktan sonra eklenmelidir.",
    ),
    topic(
      "odeme-linki",
      "Tahsilat kanalları",
      "Ödeme linki",
      "Müşteriye gönderilen link üzerinden tahsilatın oluşturulması ve izlenmesi.",
      [
        "Link oluşturma ve paylaşma",
        "Süre ve tek kullanım durumu",
        "Kullanılmış veya süresi dolmuş link",
        "Linkten oluşan ödeme kaydı",
      ],
      [
        "Link kimliği",
        "Oluşturan kullanıcı/bayi",
        "Tutar ve para birimi",
        "Açılış hatası",
      ],
      "Gizli anahtar veya tam ödeme URL'sindeki hassas parametreler paylaşılmamalıdır.",
    ),
    topic(
      "qr",
      "Tahsilat kanalları",
      "QR ile tahsilat",
      "QR üretimi, ödeme sonucu ve geçerlilik durumunun izlenmesi.",
      [
        "QR oluşturma ve gösterme",
        "QR üzerinden ödeme",
        "Süre ve kullanım durumu",
        "QR tahsilat geçmişi",
      ],
      [
        "QR/işlem kimliği",
        "Oluşturan kullanıcı",
        "Tarih-saat",
        "Cihaz ve hata ekranı",
      ],
      "QR özelliği aktif değilse kullanım adımları gösterilmemelidir.",
    ),
    topic(
      "bayi",
      "Organizasyon",
      "Bayi ve alt bayi yönetimi",
      "Firma, şube, bayi, alt bayi ve kullanıcıların tahsilat yetkileriyle ilişkisi.",
      [
        "Bayi/alt bayi oluşturma",
        "Rol ve yetkilendirme",
        "Bayiye özel taksit ve komisyon",
        "Tahsilat ve işlem geçmişi",
      ],
      ["Firma/şube/bayi", "Kullanıcı ve rol", "Beklenen işlem veya izin"],
      "Hiyerarşi ve hak ediş davranışı gerçek uygulama kuralına göre anlatılmalıdır.",
    ),
    topic(
      "mobil",
      "Mobil",
      "Mobil tahsilat",
      "Mobil uygulama ve plasiyer kullanımındaki tahsilat, QR, link ve bildirim akışları.",
      [
        "Mobil uygulamaya giriş",
        "Mobil link veya QR tahsilatı",
        "İşlem geçmişi ve bildirimler",
        "Oturum, bağlantı ve çevrimdışı kuyruk",
      ],
      [
        "Cihaz ve işletim sistemi",
        "Uygulama sürümü",
        "Kullanıcı/işlem referansı",
        "Bağlantı türü",
      ],
      "Yalnızca yayınlanmış mobil özellikler için adım adım kullanım gösterilmelidir.",
    ),
    topic(
      "raporlama",
      "Operasyon",
      "İşlem geçmişi ve raporlama",
      "Tahsilatların tarih, işlem, banka/POS veya bayi bilgileriyle incelenmesi.",
      [
        "İşlem geçmişinde arama",
        "Başarılı/başarısız işlem filtreleri",
        "Banka/POS ve bayi kırılımı",
        "Tahsilat ve komisyon raporları",
      ],
      ["Aranan tarih aralığı", "İşlem/bayi/POS", "Beklenen kayıt"],
      "Gerçek ekranda bulunmayan filtre veya rapor seçenekleri gösterilmemelidir.",
    ),
    topic(
      "mutabakat",
      "Operasyon",
      "Mutabakat",
      "AnyPay, banka/PSP ve ERP kayıtlarının aynı işlem üzerinden karşılaştırılması.",
      [
        "İşlem eşleştirme",
        "Eksik işlem",
        "Tutar veya durum uyuşmazlığı",
        "ERP/muhasebe aktarımı",
      ],
      [
        "İşlem ve mutabakat referansı",
        "Banka hareketi",
        "ERP belge numarası",
        "Beklenen/görünen tutar",
      ],
      "Tekrar aktarım öncesinde mükerrer kayıt kontrol edilmelidir.",
    ),
    topic(
      "entegrasyonlar",
      "Entegrasyonlar",
      "Banka, PSP, ERP ve API entegrasyonları",
      "Dış sistem bağlantılarının amaç, kurulum, test ve hata kontrol çerçevesi.",
      [
        "Banka/Sanal POS ve ödeme kuruluşları",
        "ERP, muhasebe ve CRM",
        "API ve Webhook",
        "Bağlantı testi, işlem akışı ve yaygın hatalar",
      ],
      ["Entegrasyon adı", "Ortam", "İşlem zamanı", "HTTP/hata kodu"],
      "Yalnızca gerçekten desteklenen entegrasyonlar listelenmeli; secret veya API anahtarı gösterilmemelidir.",
    ),
    topic(
      "guvenlik",
      "Güvenlik",
      "Güvenli kullanım",
      "Ödeme, kullanıcı, oturum ve kart verisi güvenliği için temel kullanıcı kuralları.",
      [
        "3D Secure ve güvenli ödeme",
        "Rol ve kullanıcı yetkileri",
        "Oturum güvenliği",
        "Tokenization, PCI-DSS, KVKK ve şüpheli işlemler",
      ],
      [
        "Maskeli işlem referansı",
        "Olay zamanı",
        "Etkilenen kullanıcı/işyeri",
        "Alarm veya hata kodu",
      ],
      "Secret, API key, şifre, CVV ve tam kart numarası yardım içeriğine veya forma yazılmamalıdır.",
      false,
    ),
    topic(
      "sorun-giderme",
      "Sorun giderme",
      "Yaygın AnyPay sorunları",
      "Ödeme, POS, link, QR, bayi, rapor veya entegrasyon sorunlarını doğru başlığa ayırma rehberi.",
      [
        "Ödeme gerçekleşmiyor veya kart reddediliyor",
        "3D Secure açılmıyor ya da sonuç dönmüyor",
        "Taksit/komisyon/POS beklenenden farklı",
        "Link, QR, bayi, rapor veya entegrasyon çalışmıyor",
      ],
      [
        "İşlem/kayıt referansı",
        "Tarih-saat",
        "Beklenen ve görünen sonuç",
        "Hata mesajı ve ekran görüntüsü",
      ],
      "Önce kesin işlem sonucunu doğrulayın; belirsiz ödeme durumunda işlemi tekrar etmeyin.",
      false,
    ),
  ],
  etic7: [
    topic(
      "etic7-hakkinda",
      "Başlangıç",
      "ETİC7 hakkında",
      "B2B, B2C ve katalog kullanımını ürün, sipariş, stok, ödeme ve entegrasyonlarla birleştirmeyi amaçlayan e-ticaret yapısı.",
      [
        "B2B, B2C ve katalog",
        "Ürün, kategori, müşteri, sipariş ve stok",
        "Ödeme, kampanya, kupon ve kargo",
        "SEO, raporlama ve entegrasyonlar",
      ],
      ["Kullanılan mağaza/mod", "Etkilenen süreç", "Kullanıcı rolü"],
      "Bu başlık genel kapsamı açıklar; her modülün aktifliği ilgili mağazada doğrulanmalıdır.",
      false,
    ),
    topic(
      "yonetim-paneli",
      "Başlangıç",
      "Yönetim paneli",
      "Panel girişi, menüler, kullanıcı hesabı, roller ve mağaza ayarları.",
      [
        "Panele giriş ve ana ekran",
        "Menülerin kullanımı",
        "Kullanıcı, rol ve yetki",
        "Firma, mağaza ve genel ayarlar",
      ],
      ["Kullanıcı rolü", "Erişilemeyen menü/alan", "Mağaza"],
      "Menü ve alan adları gerçek ETİC7 paneli görülmeden kesin kullanım adımı olarak yazılmamalıdır.",
    ),
    topic(
      "b2c",
      "Satış modelleri",
      "B2C kullanımı",
      "Son kullanıcının ürün görüntüleme, sepet, sipariş, ödeme ve teslimat akışı.",
      [
        "Müşteri hesabı",
        "Ürün ve sepet",
        "Sipariş ve ödeme",
        "Teslimat ve sipariş takibi",
      ],
      ["Müşteri hesabı", "Sipariş/sepet", "Mağaza ve cihaz"],
      "Yalnızca çalışan B2C adımları gerçek ekran sırasıyla gösterilmelidir.",
    ),
    topic(
      "b2b",
      "Satış modelleri",
      "B2B kullanımı",
      "Kurumsal müşteri ve bayi kullanıcılarının fiyat, görünürlük, sipariş ve yetki davranışları.",
      [
        "Kurumsal müşteri/bayi hesabı",
        "Kullanıcıya özel fiyat",
        "B2B ürün görünürlüğü",
        "B2B sipariş ve yetkilendirme",
      ],
      [
        "Firma/bayi",
        "Kullanıcı ve rol",
        "Ürün/SKU",
        "Beklenen fiyat veya yetki",
      ],
      "B2B fiyat ve görünürlük öncelikleri gerçek mağaza kuralına göre doğrulanmalıdır.",
    ),
    topic(
      "katalog",
      "Satış modelleri",
      "Katalog modu",
      "Ürünlerin fiyatlı veya fiyatsız sergilendiği katalog kullanımının kapsamı.",
      [
        "Fiyatlı/fiyatsız katalog",
        "Ürün listesi ve detayları",
        "Katalog görünürlüğü",
      ],
      ["Mağaza", "Katalog modu", "Ürün/SKU", "Beklenen görünüm"],
      "Katalog modu aktif değilse kullanım adımları gösterilmemelidir.",
    ),
    topic(
      "urun",
      "Katalog",
      "Ürün yönetimi",
      "Ürün kaydındaki temel içerik, fiyat, stok, varyant, görsel ve SEO alanları.",
      [
        "Ürün oluşturma, düzenleme, aktif/pasif ve silme",
        "Ad, açıklama, SKU, barkod, fiyat ve vergi",
        "Görsel, kategori, stok ve varyant",
        "SEO bilgileri ve ürün URL'si",
      ],
      ["Ürün ID/SKU", "Kategori/varyant", "Mağaza ve kullanıcı rolü"],
      "Alan adları ve zorunluluklar gerçek ürün formuna göre tamamlanmalıdır.",
    ),
    topic(
      "urun-gorunmuyor",
      "Sorun giderme",
      "Ürün görünmüyor",
      "Panelde bulunan bir ürünün mağazada görünmemesinin temel kontrolleri.",
      [
        "Ürün ve kategori aktifliği",
        "Stok, fiyat ve yayın durumu",
        "Varyant ve görünürlük",
        "B2B/B2C/katalog erişimi",
      ],
      [
        "Ürün ID/SKU veya URL",
        "Mağaza/mod",
        "Kullanıcı rolü",
        "Ekran görüntüsü",
      ],
      "Panel kaydı doğruysa önbellek ve arama indeksi kontrol edilmelidir.",
      false,
    ),
    topic(
      "urun-gorselleri",
      "Katalog",
      "Ürün görselleri",
      "Ana görsel ve galeri yükleme, değiştirme, silme ve görüntüleme sorunları.",
      [
        "Ana görsel ve galeri",
        "Yükleme/değiştirme/silme",
        "Dosya formatı ve boyutu",
        "Görsel yolu veya görüntülenmeme sorunu",
      ],
      [
        "Ürün ID/SKU",
        "Dosya formatı ve boyutu",
        "Hatalı URL",
        "Ekran görüntüsü",
      ],
      "Desteklenen format ve boyut sınırı gerçek yükleme bileşeninden doğrulanmalıdır.",
    ),
    topic(
      "kategori",
      "Katalog",
      "Kategori yönetimi",
      "Kategori, alt kategori, sıralama, görsel ve ürün bağlantılarının yönetimi.",
      [
        "Kategori oluşturma ve düzenleme",
        "Alt kategori ve sıralama",
        "Aktif/pasif ve mağaza görünürlüğü",
        "Ürün bağlantısı ve kategori SEO",
      ],
      [
        "Kategori kimliği/URL",
        "Üst kategori",
        "Bağlı ürün",
        "Beklenen sıralama",
      ],
      "Kategori davranışı gerçek panel alanlarına göre açıklanmalıdır.",
    ),
    topic(
      "siparis",
      "Sipariş",
      "Sipariş yönetimi",
      "Sipariş listesinden müşteri, ürün, ödeme, teslimat ve durum bilgilerinin izlenmesi.",
      [
        "Sipariş listesi ve numarası",
        "Müşteri, tarih, tutar ve ürünler",
        "Ödeme ve sipariş durumu",
        "Adres, not, iptal, iade ve geçmiş",
      ],
      ["Sipariş numarası", "Müşteri", "İşlem zamanı", "Beklenen durum"],
      "İptal ve iade yalnızca uygulamada mevcutsa kullanım adımı olarak gösterilmelidir.",
    ),
    topic(
      "siparis-sorunlari",
      "Sorun giderme",
      "Sipariş sorunları",
      "Oluşmayan, çift oluşan, bekleyen veya yanlış içerikli siparişlerin kontrolü.",
      [
        "Sipariş oluşmadı veya iki kez oluştu",
        "Ödeme yapıldı, sipariş bekliyor",
        "Tutar ya da ürünler yanlış",
        "Durum değişmiyor veya sipariş görünmüyor",
      ],
      [
        "Sipariş/ödeme numarası",
        "Müşteri",
        "Tarih-saat",
        "Beklenen/görünen sonuç",
      ],
      "Ödeme sonucu kesinleşmeden sipariş veya tahsilat tekrar oluşturulmamalıdır.",
      false,
    ),
    topic(
      "stok",
      "Stok",
      "Stok yönetimi",
      "Ürün ve varyant stoklarının güncellenmesi, hareketleri ve senkronizasyonu.",
      [
        "Stok miktarı ve hareketleri",
        "Varyant stoğu ve kritik stok",
        "Sipariş/iptal sonrası stok",
        "ERP stok senkronizasyonu ve uyuşmazlık",
      ],
      [
        "Ürün/varyant kodu",
        "Depo",
        "Beklenen/görünen stok",
        "Son senkron zamanı",
      ],
      "Stok düşme ve geri ekleme davranışı gerçek sipariş akışıyla doğrulanmalıdır.",
    ),
    topic(
      "musteri",
      "Müşteri",
      "Müşteri yönetimi",
      "Müşteri hesabı, iletişim, adres, fatura ve yetki bilgilerinin kapsamı.",
      [
        "Müşteri oluşturma ve hesap durumu",
        "Telefon, e-posta ve adres",
        "Fatura bilgileri ve siparişler",
        "Şifre sıfırlama, grup ve yetkiler",
      ],
      ["Müşteri hesabı/e-posta", "Mağaza", "Etkilenen işlem"],
      "Kişisel veriler yalnızca gerekli ölçüde ve maskeli biçimde kullanılmalıdır.",
    ),
    topic(
      "kampanya",
      "Pazarlama",
      "Kampanya yönetimi",
      "Ürün veya kategori kampanyalarının tarih, koşul ve görünürlük bilgilerinin yönetimi.",
      [
        "Kampanya oluşturma/düzenleme",
        "Aktiflik ve tarih aralığı",
        "Ürün/kategori kapsamı",
        "Koşullar ve görünmeme sorunu",
      ],
      ["Kampanya adı/kodu", "Tarih aralığı", "Ürün/kategori", "Müşteri/mod"],
      "Kampanya özelliği aktif değilse bu içerik kullanım rehberi olarak gösterilmemelidir.",
    ),
    topic(
      "kupon",
      "Pazarlama",
      "İndirim ve kupon",
      "Kupon kodu, indirim, tarih, limit ve kapsam koşullarının değerlendirilmesi.",
      [
        "Kupon oluşturma ve aktiflik",
        "Oran/tutar ve minimum sepet",
        "Başlangıç-bitiş ve kullanım limiti",
        "Ürün/kategori sınırı ve çalışmama sorunu",
      ],
      ["Kupon kodu", "Sepet tutarı", "Müşteri", "Tarih-saat", "Hata mesajı"],
      "İndirim hesaplama sırası gerçek sepet kuralına göre doğrulanmalıdır.",
    ),
    topic(
      "odeme",
      "Sipariş",
      "Ödeme yönetimi",
      "Siparişe bağlı ödeme yöntemi, Sanal POS, 3D Secure, taksit ve durum takibi.",
      [
        "Ödeme yöntemleri ve kartla ödeme",
        "Sanal POS ve 3D Secure",
        "Taksit ve ödeme durumu",
        "Sipariş-ödeme eşleşmesi ve hatalar",
      ],
      [
        "Sipariş ve işlem numarası",
        "Banka/PSP",
        "Tutar ve tarih-saat",
        "Hata kodu",
      ],
      "Belirsiz ödeme durumunda yeniden tahsilat yapılmamalıdır.",
    ),
    topic(
      "kargo",
      "Sipariş",
      "Kargo yönetimi",
      "Siparişin kargo firması, ücret, çıkış, takip ve entegrasyon bilgilerinin yönetimi.",
      [
        "Kargo firması/yöntemi ve ücret",
        "Siparişi kargoya verme",
        "Takip numarası ve durum",
        "Kargo API hatası ve müşteriye gösterim",
      ],
      [
        "Sipariş numarası",
        "Kargo firması",
        "Takip numarası",
        "Son doğru durum",
      ],
      "Kargo entegrasyonu aktif değilse API adımları gösterilmemelidir.",
    ),
    topic(
      "seo",
      "Pazarlama",
      "SEO yönetimi",
      "Ürün, kategori ve sayfalardaki arama motoru bilgilerinin kapsamı.",
      [
        "SEO başlığı ve meta description",
        "SEO URL",
        "Ürün/kategori/sayfa SEO",
        "Sitemap ve arama motoru görünürlüğü",
      ],
      ["İlgili URL", "Sayfa/ürün/kategori", "Beklenen ve görünen meta bilgi"],
      "Alan isimleri gerçek SEO formuna göre gösterilmelidir.",
    ),
    topic(
      "google",
      "Entegrasyonlar",
      "Google entegrasyonları",
      "Analytics, Ads, Merchant Center, dönüşüm ve ürün feed'i bağlantılarının destek çerçevesi.",
      [
        "Servisin amacı ve gereken bilgiler",
        "Kurulum ve bağlantı testi",
        "Feed/olay senkronizasyonu",
        "Yaygın hata ve doğrulama",
      ],
      [
        "Google servisi",
        "Hesap/akış adı",
        "Etkilenen URL/ürün",
        "Hata ve son başarılı zaman",
      ],
      "Yalnızca bağlı ve çalışan Google servisleri kullanıcıya gösterilmelidir.",
    ),
    topic(
      "meta",
      "Entegrasyonlar",
      "Meta entegrasyonları",
      "Facebook, Instagram, Meta Shop, katalog ve ürün feed'i bağlantılarının kapsamı.",
      [
        "Hesap ve katalog bağlantısı",
        "Ürün feed'i",
        "Senkronizasyon",
        "Bağlantı ve entegrasyon hataları",
      ],
      ["Meta hesabı/katalog", "Ürün/SKU", "Hata mesajı", "Son senkron zamanı"],
      "Meta entegrasyonu mevcut değilse aktif özellik olarak anlatılmamalıdır.",
    ),
    topic(
      "erp",
      "Entegrasyonlar",
      "ERP ve muhasebe entegrasyonları",
      "Ürün, stok, sipariş ve müşteri verilerinin kurumsal sistemlerle aktarımı.",
      [
        "ERP/muhasebe bağlantısı",
        "Ürün, stok, sipariş ve müşteri aktarımı",
        "Senkronizasyon",
        "Bağlantı hatası ve veri uyuşmazlığı",
      ],
      [
        "Entegrasyon adı",
        "Kayıt/belge numarası",
        "İşlem zamanı",
        "Hata mesajı",
      ],
      "Yalnızca gerçekten desteklenen ERP ve muhasebe ürünleri listelenmelidir.",
    ),
    topic(
      "api",
      "Entegrasyonlar",
      "API ve harici entegrasyonlar",
      "Yetkilendirme, veri aktarımı, Webhook ve hata durumlarının kullanıcıya açık çerçevesi.",
      [
        "API'nin kullanım amacı",
        "Yetkilendirme ve bağlantı",
        "Veri aktarımı ve Webhook",
        "Senkronizasyon ve hata durumları",
      ],
      [
        "Endpoint/entegrasyon adı",
        "İşlem zamanı",
        "HTTP/hata kodu",
        "Maskeli istek referansı",
      ],
      "Credential, secret, token veya API anahtarı yardım içeriğinde gösterilmemelidir.",
    ),
    topic(
      "raporlama",
      "Raporlama",
      "Raporlama",
      "Satış, sipariş, ürün, stok ve müşteri verilerinin mevcut filtrelerle incelenmesi.",
      [
        "Satış ve sipariş raporları",
        "Ürün ve stok raporları",
        "Müşteri raporları",
        "Tarih filtreleri ve satış performansı",
      ],
      ["Rapor adı", "Tarih aralığı", "Uygulanan filtre", "Beklenen kayıt"],
      "Yalnızca gerçek rapor ve filtre seçenekleri listelenmelidir.",
    ),
    topic(
      "sorun-giderme",
      "Sorun giderme",
      "Yaygın ETİC7 sorunları",
      "Katalog, sipariş, müşteri, kampanya, kargo ve entegrasyon sorunlarını doğru başlığa ayırma rehberi.",
      [
        "Ürün/görsel/fiyat/stok/kategori görünmüyor",
        "Sipariş veya ödeme oluşmuyor/güncellenmiyor",
        "Müşteri girişi, kupon veya kampanya çalışmıyor",
        "Kargo, ERP, Google veya Meta senkronize olmuyor",
      ],
      [
        "İlgili kayıt numarası",
        "Mağaza ve kullanıcı",
        "Tarih-saat",
        "Beklenen/görünen sonuç",
        "Ekran görüntüsü",
      ],
      "Sorunun türüne göre yalnızca gerekli bilgiler istenmelidir.",
      false,
    ),
    topic(
      "gerekli-bilgiler",
      "Sorun giderme",
      "Sorunu anlamak için gerekli bilgiler",
      "Her sorunda bütün alanları istemek yerine konuya göre doğru bilgileri toplama rehberi.",
      [
        "Sipariş: sipariş numarası",
        "Ürün: ürün ID/SKU",
        "Müşteri: hesap/e-posta",
        "Kargo: sipariş ve takip numarası",
        "Entegrasyon: ad, zaman ve hata",
        "Görsel: ürün/sayfa ve ekran görüntüsü",
      ],
      ["Sorun türü", "İlgili kayıt", "Beklenen ve görünen sonuç"],
      "Parola, tam kart numarası, CVV, API anahtarı veya gereksiz kişisel veri paylaşılmamalıdır.",
      false,
    ),
  ],
};
