import { Router } from "express";
import { authorize } from "../middleware/auth.js";
import * as service from "../services/management.service.js";
import * as schema from "../validators/management.js";
import { idSchema, paginationSchema } from "../validators/index.js";
import { upload, withStoredUploads, uploadRoot } from '../services/uploads.service.js';
import path from 'node:path';

export const managementRouter = Router();
const admin = authorize("ADMIN");
const staff = authorize("ADMIN", "SUPERVISOR", "AGENT");
managementRouter.get("/users", admin, async (req, res) => res.json({ success: true, ...await service.users(req.actor, schema.directoryQuery.parse(req.query)) }));
managementRouter.get("/users/:id", admin, async (req, res) => res.json({ success: true, data: await service.user(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.post("/users", admin, async (req, res) => res.status(201).json({ success: true, data: await service.createUser(req.actor, schema.createUserSchema.parse(req.body)) }));
managementRouter.patch("/users/:id", admin, async (req, res) => res.json({ success: true, data: await service.updateUser(req.actor, idSchema.parse(req.params.id), schema.updateUserSchema.parse(req.body)) }));
managementRouter.delete('/users/:id', admin, async (req, res) => res.json({ success: true, data: await service.deleteUser(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.get("/customers", staff, async (req, res) => res.json({ success: true, ...await service.users(req.actor, schema.directoryQuery.parse(req.query), true) }));
managementRouter.get("/customers/:id", staff, async (req, res) => res.json({ success: true, data: await service.customer(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.get("/customers/:id/files", staff, async (req, res) => res.json({ success: true, data: await service.customerFiles(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.delete("/customers/:id/files/:fileId", staff, async (req, res) => { await service.deleteCustomerFile(req.actor, idSchema.parse(req.params.id), idSchema.parse(req.params.fileId)); res.json({ success: true, data: null }); });
managementRouter.get("/customers/:id/files/:fileId/download", staff, async (req, res, next) => {
  const file = await service.customerFile(req.actor, idSchema.parse(req.params.id), idSchema.parse(req.params.fileId));
  res.type(file.mimeType);
  res.setHeader('Cache-Control', 'private, no-store');
  res.download(path.join(uploadRoot, file.storageKey), file.originalName, error => { if (error && !res.headersSent) next(error); });
});
managementRouter.post("/customers", staff, upload, async (req, res) => res.status(201).json({ success: true, data: await withStoredUploads(req.files as Express.Multer.File[], files => service.createCustomer(req.actor, schema.createCustomerSchema.parse(req.body), files)) }));
managementRouter.patch("/customers/:id", staff, upload, async (req, res) => res.json({ success: true, data: await withStoredUploads(req.files as Express.Multer.File[], files => service.updateCustomer(req.actor, idSchema.parse(req.params.id), schema.updateCustomerSchema.parse(req.body), files)) }));
managementRouter.delete("/customers/:id", staff, async (req, res) => res.json({ success: true, data: await service.deleteCustomer(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.get("/departments/:id/agents", staff, async (req, res) => res.json({ success: true, ...await service.departmentAgents(req.actor, idSchema.parse(req.params.id), schema.searchQuery.parse(req.query)) }));
managementRouter.patch("/departments/:id", admin, async (req, res) => res.json({ success: true, data: await service.updateDepartment(req.actor, idSchema.parse(req.params.id), schema.departmentSchema.parse(req.body)) }));
managementRouter.delete("/departments/:id", admin, async (req, res) => res.json({ success: true, data: await service.deleteDepartment(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.get("/tags", async (req, res) => res.json({ success: true, ...await service.tags(schema.searchQuery.parse(req.query)) }));
managementRouter.post("/tags", admin, async (req, res) => res.status(201).json({ success: true, data: await service.writeTag(req.actor, schema.tagSchema.parse(req.body)) }));
managementRouter.patch("/tags/:id", admin, async (req, res) => res.json({ success: true, data: await service.writeTag(req.actor, schema.updateTagSchema.parse(req.body), idSchema.parse(req.params.id)) }));
managementRouter.delete("/tags/:id", admin, async (req, res) => { await service.deleteTag(req.actor, idSchema.parse(req.params.id)); res.json({ success: true, data: null }); });
managementRouter.get("/status-options", staff, async (req, res) => res.json({ success: true, ...await service.statusOptions(schema.searchQuery.parse(req.query)) }));
managementRouter.post("/status-options", admin, async (req, res) => res.status(201).json({ success: true, data: await service.writeStatusOption(req.actor, schema.statusOptionSchema.parse(req.body)) }));
managementRouter.patch("/status-options/:id", admin, async (req, res) => res.json({ success: true, data: await service.writeStatusOption(req.actor, schema.updateStatusOptionSchema.parse(req.body), idSchema.parse(req.params.id)) }));
managementRouter.delete("/status-options/:id", admin, async (req, res) => { await service.deleteStatusOption(req.actor, idSchema.parse(req.params.id)); res.json({ success: true, data: null }); });
managementRouter.get("/priority-options", staff, async (req, res) => res.json({ success: true, ...await service.priorityOptions(schema.searchQuery.parse(req.query)) }));
managementRouter.post("/priority-options", admin, async (req, res) => res.status(201).json({ success: true, data: await service.writePriorityOption(req.actor, schema.priorityOptionSchema.parse(req.body)) }));
managementRouter.patch("/priority-options/:id", admin, async (req, res) => res.json({ success: true, data: await service.writePriorityOption(req.actor, schema.updatePriorityOptionSchema.parse(req.body), idSchema.parse(req.params.id)) }));
managementRouter.delete("/priority-options/:id", admin, async (req, res) => { await service.deletePriorityOption(req.actor, idSchema.parse(req.params.id)); res.json({ success: true, data: null }); });
managementRouter.get("/websites", staff, async (req, res) => res.json({ success: true, ...await service.websites(schema.searchQuery.parse(req.query)) }));
managementRouter.post("/websites", admin, async (req, res) => res.status(201).json({ success: true, data: await service.writeWebsite(req.actor, schema.websiteSchema.parse(req.body)) }));
managementRouter.patch("/websites/:id", admin, async (req, res) => res.json({ success: true, data: await service.writeWebsite(req.actor, schema.updateWebsiteSchema.parse(req.body), idSchema.parse(req.params.id)) }));
managementRouter.delete("/websites/:id", admin, async (req, res) => { await service.deleteWebsite(req.actor, idSchema.parse(req.params.id)); res.json({ success: true, data: null }); });
managementRouter.get("/saved-replies", staff, async (req, res) => res.json({ success: true, ...await service.savedReplies(req.actor, schema.searchQuery.parse(req.query)) }));
managementRouter.post("/saved-replies", staff, async (req, res) => res.status(201).json({ success: true, data: await service.writeSavedReply(req.actor, schema.savedReplySchema.parse(req.body)) }));
managementRouter.patch("/saved-replies/:id", staff, async (req, res) => res.json({ success: true, data: await service.writeSavedReply(req.actor, schema.updateSavedReplySchema.parse(req.body), idSchema.parse(req.params.id)) }));
managementRouter.delete("/saved-replies/:id", staff, async (req, res) => { await service.deleteSavedReply(req.actor, idSchema.parse(req.params.id)); res.json({ success: true, data: null }); });
managementRouter.get("/notifications", async (req, res) => res.json({ success: true, ...await service.notifications(req.actor, schema.notificationQuery.parse(req.query)) }));
managementRouter.patch("/notifications/read-all", async (req, res) => res.json({ success: true, data: await service.readNotifications(req.actor) }));
managementRouter.patch("/notifications/:id/read", async (req, res) => res.json({ success: true, data: await service.readNotifications(req.actor, idSchema.parse(req.params.id)) }));
managementRouter.delete("/notifications", async (req, res) => res.json({ success: true, data: await service.deleteNotifications(req.actor, schema.notificationDeleteQuery.parse(req.query).period) }));
managementRouter.delete("/notifications/visible", async (req, res) => res.json({ success: true, data: await service.deleteVisibleNotifications(req.actor, schema.notificationVisibleDeleteSchema.parse(req.body).ids) }));
managementRouter.get("/activity-logs", admin, async (req, res) => res.json({ success: true, ...await service.activityLogs(req.actor, schema.activityQuery.parse(req.query)) }));
managementRouter.delete("/activity-logs", admin, async (req, res) => res.json({ success: true, data: await service.deleteActivityLogs(req.actor, schema.activityDeleteQuery.parse(req.query).period) }));
managementRouter.get("/integrations", admin, async (req, res) => res.json({ success: true, data: await service.integrationSettings(req.actor) }));
managementRouter.put("/integrations", admin, async (req, res) => res.json({ success: true, data: await service.updateIntegrationSettings(req.actor, schema.integrationSettingsSchema.parse(req.body)) }));
managementRouter.post("/integrations/test", admin, async (req, res) => res.json({ success: true, data: await service.testIntegration(req.actor, schema.integrationTestSchema.parse(req.body).channel) }));
managementRouter.get("/response-time-settings", admin, async (req, res) => res.json({ success: true, data: await service.responseTimeSettings(req.actor) }));
managementRouter.put("/response-time-settings", admin, async (req, res) => res.json({ success: true, data: await service.updateResponseTimeSettings(req.actor, schema.responseTimeSettingsSchema.parse(req.body)) }));
managementRouter.get("/notification-settings", admin, async (req, res) => res.json({ success: true, data: await service.notificationSettings(req.actor) }));
managementRouter.put("/notification-settings", admin, async (req, res) => res.json({ success: true, data: await service.updateNotificationSettings(req.actor, schema.notificationSettingsSchema.parse(req.body)) }));
managementRouter.get("/profile", async (req, res) => res.json({ success: true, data: await service.profile(req.actor) }));
managementRouter.patch("/profile", async (req, res) => res.json({ success: true, data: await service.updateProfile(req.actor, schema.profileSchema.parse(req.body)) }));
managementRouter.get("/reports", authorize("ADMIN", "SUPERVISOR"), async (req, res) => res.json({ success: true, data: await service.reports(req.actor, paginationSchema.parse(req.query)) }));
